### PR TITLE
cef: Update to latest stable release

### PR DESCRIPTION
**Pull request by aiden-jeffrey**

### CODE REVIEW

**Comment by MathieuDuponchelle** [comment]
This doesn't appear to build on my end:

```
/home/meh/devel/gstreamer/sandbox/gstcefsrc/third_party/cef/cef_binary_129.0.10+ge52707f+chromium-129.0.6668.71_linux64/libcef_dll/wrapper/cef_message_router.cc: In member function ‘virtual bool {anonymous}::CefMessageRouterBrowserSideImpl::AddHandler(CefMessageRouterBrowserSide::Handler*, bool)’:
/home/meh/devel/gstreamer/sandbox/gstcefsrc/third_party/cef/cef_binary_129.0.10+ge52707f+chromium-129.0.6668.71_linux64/libcef_dll/wrapper/cef_message_router.cc:201:18: error: no matching function for call to ‘find(std::vector<CefMessageRouterBrowserSide::Handler*>::iterator, std::vector<CefMessageRouterBrowserSide::Handler*>::iterator, CefMessageRouterBrowserSide::Handler*&)’
  201 |     if (std::find(handlers_.begin(), handlers_.end(), handler) ==
      |         ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/14/bits/locale_facets.h:48,
                 from /usr/include/c++/14/bits/basic_ios.h:37,
                 from /usr/include/c++/14/ios:46,
                 from /usr/include/c++/14/istream:40,
                 from /usr/include/c++/14/sstream:40,
                 from /home/meh/devel/gstreamer/sandbox/gstcefsrc/third_party/cef/cef_binary_129.0.10+ge52707f+chromium-129.0.6668.71_linux64/include/base/cef_logging.h:183,
                 from /home/meh/devel/gstreamer/sandbox/gstcefsrc/third_party/cef/cef_binary_129.0.10+ge52707f+chromium-129.0.6668.71_linux64/include/base/cef_ref_counted.h:51,
                 from /home/meh/devel/gstreamer/sandbox/gstcefsrc/third_party/cef/cef_binary_129.0.10+ge52707f+chromium-129.0.6668.71_linux64/include/wrapper/cef_message_router.h:40,
                 from /home/meh/devel/gstreamer/sandbox/gstcefsrc/third_party/cef/cef_binary_129.0.10+ge52707f+chromium-129.0.6668.71_linux64/libcef_dll/wrapper/cef_message_router.cc:5:
/usr/include/c++/14/bits/streambuf_iterator.h:435:5: note: candidate: ‘template<class _CharT2> typename __gnu_cxx::__enable_if<std::__is_char<_CharT2>::__value, std::istreambuf_iterator<_CharT> >::__type std::find(istreambuf_iterator<_CharT>, istreambuf_iterator<_CharT>, const _CharT2&)’
  435 |     find(istreambuf_iterator<_CharT> __first,
      |     ^~~~
/usr/include/c++/14/bits/streambuf_iterator.h:435:5: note:   template argument deduction/substitution failed:
/home/meh/devel/gstreamer/sandbox/gstcefsrc/third_party/cef/cef_binary_129.0.10+ge52707f+chromium-129.0.6668.71_linux64/libcef_dll/wrapper/cef_message_router.cc:201:18: note:   ‘__gnu_cxx::__normal_iterator<CefMessageRouterBrowserSide::Handler**, std::vector<CefMessageRouterBrowserSide::Handler*> >’ is not derived from ‘std::istreambuf_iterator<_CharT>’
  201 |     if (std::find(handlers_.begin(), handlers_.end(), handler) ==
      |         ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/meh/devel/gstreamer/sandbox/gstcefsrc/third_party/cef/cef_binary_129.0.10+ge52707f+chromium-129.0.6668.71_linux64/libcef_dll/wrapper/cef_message_router.cc: In member function ‘virtual bool {anonymous}::CefMessageRouterBrowserSideImpl::RemoveHandler(CefMessageRouterBrowserSide::Handler*)’:
/home/meh/devel/gstreamer/sandbox/gstcefsrc/third_party/cef/cef_binary_129.0.10+ge52707f+chromium-129.0.6668.71_linux64/libcef_dll/wrapper/cef_message_router.cc:211:24: error: no matching function for call to ‘find(std::vector<CefMessageRouterBrowserSide::Handler*>::iterator, std::vector<CefMessageRouterBrowserSide::Handler*>::iterator, CefMessageRouterBrowserSide::Handler*&)’
  211 |     auto it = std::find(handlers_.begin(), handlers_.end(), handler);
      |               ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/14/bits/streambuf_iterator.h:435:5: note: candidate: ‘template<class _CharT2> typename __gnu_cxx::__enable_if<std::__is_char<_CharT2>::__value, std::istreambuf_iterator<_CharT> >::__type std::find(istreambuf_iterator<_CharT>, istreambuf_iterator<_CharT>, const _CharT2&)’
  435 |     find(istreambuf_iterator<_CharT> __first,
      |     ^~~~
/usr/include/c++/14/bits/streambuf_iterator.h:435:5: note:   template argument deduction/substitution failed:
/home/meh/devel/gstreamer/sandbox/gstcefsrc/third_party/cef/cef_binary_129.0.10+ge52707f+chromium-129.0.6668.71_linux64/libcef_dll/wrapper/cef_message_router.cc:211:24: note:   ‘__gnu_cxx::__normal_iterator<CefMessageRouterBrowserSide::Handler**, std::vector<CefMessageRouterBrowserSide::Handler*> >’ is not derived from ‘std::istreambuf_iterator<_CharT>’
  211 |     auto it = std::find(handlers_.begin(), handlers_.end(), handler);
      |               ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-undefined-var-template’ may have been intended to silence earlier diagnostics
make[2]: *** [libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/build.make:2568: libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/wrapper/cef_message_router.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:154: libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by aiden-jeffrey** [comment]
> This doesn't appear to build on my end:

Strange. It works for me. Assuming you've tried clearing the third_party and build directories?

**Comment by MathieuDuponchelle** [comment]
yes, I cleared the build directory, I don't think clearing third_party is needed but I can try :)

**Comment by MathieuDuponchelle** [comment]
no difference after clearing and rebuilding :|

**Comment by MathieuDuponchelle** [comment]
This is fixed by dropping a `#include <algorithm>` in third_party/cef/cef_binary_129.0.10+ge52707f+chromium-129.0.6668.71_linux64/include/base/cef_logging.h but that's obviously not a useful solution

**Comment by MathieuDuponchelle** [comment]
So, not sure what to do here, I filed https://github.com/chromiumembedded/cef/issues/3804, with chance we might get a fix for a future release :)

**Comment by fraxinas** [comment]
Hi @aiden-jeffrey i have trouble building https://github.com/centricular/gstcefsrc/commit/306a4530e80cf9fc11c11877115a026af09e2467 an top of CEF 129.0.13+g965d61d+chromium-129.0.6668.101 & GST 1.24.8:

[22/199] Building CXX object CMakeFiles/gstcef.dir/gstcefsrc.cc.o
09:31:17   FAILED: CMakeFiles/gstcef.dir/gstcefsrc.cc.o
09:31:17   /usr/bin/c++ -DNDEBUG -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -Dgstcef_EXPORTS -I/gstcefsrc/third_party/cef_binary_129.0.13+g965d61d+chromium-129.0.6668.101_linux64_minimal -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -O3 -DNDEBUG -fPIC -fno-strict-aliasing -fPIC -fstack-protector -funwind-tables -fvisibility=hidden --param=ssp-buffer-size=4 -pipe -pthread -Wall -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-error=comment -Wno-comment -Wno-deprecated-declarations -m64 -march=x86-64 -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -std=c++17 -Wsign-compare -Wno-undefined-var-template -Wno-literal-suffix -Wno-narrowing -Wno-attributes -O2 -fdata-sections -ffunction-sections -fno-ident -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -MD -MT CMakeFiles/gstcef.dir/gstcefsrc.cc.o -MF CMakeFiles/gstcef.dir/gstcefsrc.cc.o.d -o CMakeFiles/gstcef.dir/gstcefsrc.cc.o -c /gstcefsrc/gstcefsrc.cc
```
09:31:17   /gstcefsrc/gstcefsrc.cc:499:18: error: ‘virtual void BrowserClient::OnRenderProcessTerminated(CefRefPtr<CefBrowser>, CefRequestHandler::TerminationStatus)’ marked ‘override’, but does not override
09:31:17     499 |     virtual void OnRenderProcessTerminated(CefRefPtr<CefBrowser> browser, TerminationStatus status) override
09:31:17         |                  ^~~~~~~~~~~~~~~~~~~~~~~~~
09:31:17   cc1plus: note: unrecognized command-line option ‘-Wno-undefined-var-template’ may have been intended to silence earlier diagnostics
```

**Comment by aiden-jeffrey** [comment]
> Hi @aiden-jeffrey i have trouble 

You'll have to apply the changes from this patch to the OnRenderProcessTerminated definition.

**Comment by aiden-jeffrey** [comment]
@MathieuDuponchelle - updated this to include the fix, so this should build for you now (I think).

**Comment by MathieuDuponchelle** [comment]
It does build now, thanks :)

**Pull request merged**
