### PR TITLE
properties: Move gpu and chrome_extra_flags to env vars

### PR DESCRIPTION
**Pull request by aiden-jeffrey**
See https://github.com/centricular/gstcefsrc/pull/90#issuecomment-2393937044

### CODE REVIEW

**Comment by MathieuDuponchelle** [comment]
Nice, I'll try and make time to look in detail during the hackfest, do we need the same thing for `sandbox` and `js_flags`? I see that those are used for CEF initialization as well :/

**Comment by aiden-jeffrey** [comment]
> Nice, I'll try and make time to look in detail during the hackfest, do we need the same thing for `sandbox` and `js_flags`? I see that those are used for CEF initialization as well :/

Ah good point, I'll go though things carefully tomorrow.

**Comment by MathieuDuponchelle** [comment]
Looks good to me, that's annoyingly close to all the properties besides `url` :( Can you just add documentation for all the environment variables to a dedicated section in the README? Thanks again!

**Comment by MathieuDuponchelle** [comment]
Perfect, thanks again :)

**Pull request merged**
