### PR TITLE
Fix bad audio metadata (issues #73)

### PR DESCRIPTION
**Pull request by SteveMcFarlin**
It looks like issue #73 was never addressed. This PR has the suggested fix.

### CODE REVIEW

**Comment by MathieuDuponchelle** [comment]
lgtm thanks :)

**Comment by heftig** [comment]
Shouldn't this be using `BPF` instead of `BPS`?

**Comment by SteveMcFarlin** [comment]
@heftig I am not sure of the answer here. You might want to open an issue if you think BPF is the right choice.

**Comment by MathieuDuponchelle** [comment]
Why would `BPF` be correct here? The third parameter to `gst_buffer_add_audio_meta` is a number of samples no?

**Comment by heftig** [comment]
`gst_buffer_add_audio_meta` expects the number of samples in the buffer. The wording is a bit ambiguous, but the example given for non-interleaved layout makes it clear that the buffer size should be equal to `channels * samples * sample_stride`.

`BPS` produces the bytes per sample (the `sample_stride`), while `BPF` produces the bytes per frame (`channels * sample_stride`).

So in the case of a non-mono stream I'd expect the meta to still be broken.

**Comment by MathieuDuponchelle** [comment]
Please see my answer [here](https://github.com/centricular/gstcefsrc/issues/73#issuecomment-1701008590)

**Pull request merged**
