### PR TITLE
Add "--enable-media-stream" command-line flag used to validate local …

### PR DESCRIPTION
**Pull request by thierryg**
…ressources such as a webcam.

This is quite usefull with webrtc app for instance such as http://apprtc.appspot.com/.

### CODE REVIEW

**Comment by MathieuDuponchelle** [comment]
Seems OK to me. We really should have a property to allow specifying extra command line parameters, but this seems like a sane default. Thanks!

**Comment by thierryg** [comment]
Indeed, it could be a default parameter to cef without any other flag for
cefsrc.

Regards

Thierry GAYET
Mobile : +33.663.849.589
Skype : tux35220

**Comment by MathieuDuponchelle** [comment]
That's another question, but not what I meant here :)

**Comment by thierryg** [comment]
yes, on having a property to pass command line parameters to cef it's an
interesting idea.

Regards

Thierry GAYET
Mobile : +33.663.849.589
Skype : tux35220

**Comment by MathieuDuponchelle** [comment]
just needs doing really :D

**Pull request merged**
