### PR TITLE
Add pr build test github action

### PR DESCRIPTION
**Pull request by reinismu**
Some nice to have thingy :) 

Later if there is a need could test that we can record a video as well

Tested here https://github.com/reinismu/gstcefsrc/pull/1

### CODE REVIEW

**Comment by MathieuDuponchelle** [comment]
nice, keep em coming :)

**Comment by reinismu** [comment]
It seems that github actions are disables in this repo. You can enable them in settings

**Comment by MathieuDuponchelle** [comment]
hm, am I looking in the wrong place? 
Screenshot from 2021-03-03 01-07-53

**Comment by reinismu** [comment]
Thought it would run on this PR as well. I guess will have to check next PRs

**Comment by reinismu** [comment]
Not sure if it needs more :thinking: Would be nice to have it in rust tho :) 
Now compiling cef with all codecs so could stream websites with video playing in background uhh takes so long

**Comment by MathieuDuponchelle** [comment]
It would be nice yes, I have no idea if there exist complete enough bindings for that purpose, and I'm definitely not looking to implement any myself :)

**Pull request merged**
